header:
  version: 11
machine: bleedingbone
distro: tacos
target:
  - taco
repos:
  meta-tacos:
    layers:
      meta-tacos:
  beskar:
    url: "https://github.com/team-anant/beskar.git"
    branch: "master"
    layers:
      meta-beskar:
  openembedded-core:
    url: "https://github.com/openembedded/openembedded-core.git"
    branch: "walnascar"
    layers:
      meta:
  bitbake:
    url: "https://github.com/openembedded/bitbake.git"
    branch: "2.12"
    layers:
      .: excluded
  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "walnascar"
    layers:
      meta-arm-toolchain:
      meta-arm:
  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: master
    # commit: 118946e71938640d753022d7fe3e515b4b83e818
    layers:
      meta-ti-bsp:
      meta-beagle:
local_conf_header:
  meta-kiss: |
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES = "debug-tweaks"
